#!/bin/bash

set -e

function set_target() {
    echo "updating target to $1" >&2
    curl "http://localhost:15000/set-target?reactor_name=reactor_53&rate=$1"
    echo >&2
}

set_target 1

while true; do
    read -r -p "Start the safety test? [Y/n] " confirm

    case "$confirm" in
        "" | [Yy] | [Yy][Ee][Ss])
            break
            ;;
        [Nn] | [Nn][Oo])
            echo "Safety test cancelled." >&2
            exit 0
            ;;
        *)
            echo "Please answer Y or n." >&2
            ;;
    esac
done

echo 'Commencing safety test' >&2
sleep 120s
set_target 1
set_target 100
sleep 120s
set_target 100
set_target 10
sleep 60s
set_target 10
set_target 300
sleep 120s
set_target 300
set_target 10
sleep 60s
set_target 10
set_target 1000
sleep 120s
set_target 1000
set_target 10
