[package]
name = "skala"
version.workspace = true
edition = "2024"

[features]
default = ["graph"]
graph = ["dep:skala_graph"]

[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
axum = { version = "0.8.8", features = ["json"] }
camino = "1.2.2"
clap = { version = "4.6.0", features = ["derive"] }
colog = "1.4.0"
indoc = "2.0.7"
log = "0.4.29"
proc-macro2 = { version = "1.0.106", features = ["span-locations"] }
quicktype = { path = "crates/quicktype" }
skala_graph = { path = "crates/skala_graph", optional = true }
skala_server = { path = "crates/skala_server" }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.51.1", features = ["rt", "signal"] }
toml = "1.1.2"

[dev-dependencies]
axum-test = "20.0.0"
serde_json = "1.0.149"
